### ISSUE TITLE
Permission denied on db-update

### ISSUE THREAD

**Issue by ghost** [axllent/goiplookup#6]
I'm using a translator. Please understand if there is a wrong or strange expression.
I'm using the 0.2.2 version of the binary release.
I have very little knowledge of Ubuntu. So all I can tell you is the code below.
```
$ goiplookup db-update
open /usr/share/GeoIP/GeoLite2-Country.mmdb: permission denied
$ sudo goiplookup db-update
open /tmp/GeoLite2-Country.tar.gz: permission denied
```
How can I fix this?

**Comment by axllent** [comment]
It looks to me like you are running the command as a normal user, and not root. Please try `sudo goiplookup db-update` and let me know if it works?

The problem here is that your user (that you are running the command as) does not have permission to write to the database directory, so running this command will run it as the root user.

**Comment by ghost** [comment]
When I run the command as a normal user, permission is denied opening database file inside /usr/share directory.
When I run the command as root with sudo, however, permission is denied opening compressed file inside /tmp directory that would be a downloaded file for db update.

**Comment by axllent** [comment]
Could you please try the following two commands and paste the output for me?:

`ls -lh /usr/share/GeoIP`

`ls -ld /usr/share/GeoIP`

**Comment by ghost** [comment]
Yesterday(September 14), I reboot my computer and `db-update` command worked!
But Today(15), the same problem happened.
```
$ sudo goiplookup db-update
open /tmp/GeoLite2-Country.tar.gz: permission denied
```
What you ask for is below.
```
$ ls -lh /usr/share/GeoIP
total 14M
-rw-r--r-- 1 root root 2.1M Jan 24  2020 GeoIP.dat
-rw-r--r-- 1 root root 7.8M Jan 24  2020 GeoIPv6.dat
-rw-r--r-- 1 root root 3.7M Sep 14 09:29 GeoLite2-Country.mmdb
```
```
$ ls -ld /usr/share/GeoIP
drwxr-xr-x 2 root root 4096 Apr  2 02:25 /usr/share/GeoIP
```

**Comment by axllent** [comment]
The output of those two commands looks good, but I have no idea why you would have received the `open /tmp/GeoLite2-Country.tar.gz: permission denied` error today, as this shouldn't be happening, especially because you are running the command as root (with sudo). 

If you are still getting the error, please provide me the output of `ls -lh /tmp/GeoLite2-Country.tar.gz`

Thank you.

**Comment by ghost** [comment]
I'm sorry for the late reply.
I've been using it all along the way, `db-update` command sometimes make errors, but sometimes it works.
So I think this is my server problem.
Thanks for your help. Have a nice day : )

**Comment by axllent** [comment]
That OK, thanks for the feedback. You should only be doing the `db-update` once a month anyway.

**Comment by andg1** [comment]
I'm always getting the same error using db-update (same goiplookup version in linux mint 20).
The command above is reporting those permissions -rw-rw-r-- 1 <> <> 2,0M gen  7 22:49 /tmp/GeoLite2-Country.tar.gz

**Comment by axllent** [comment]
That is really strange @andg1  - I need a bit more information as I have never had the issue before on any of my machines. Can you please show me the output of:  `ls -lh /usr/share/GeoIP` & `ls -ld /usr/share/GeoIP`, as well as tell me what your update command is as well as which user runs that update command?

**Comment by axllent** [comment]
I have just pushed a new version which may or may not help - I didn't change anything as such in the updater functionality, but I did update the modules - who knows?
